### PR TITLE
updated docs in response to #183

### PR DESCRIPTION
**Pull request by stedy**

### CODE REVIEW

**Comment by gfinak** [comment]
Did you update just the html or the Rmd file as well?

**Comment by stedy** [comment]
Just the html, if that’s autogenerated I can update the Rmd as well

**Comment by gfinak** [comment]
Yes, the html vignettes are autogenerated from the Rmd vignettes. So the moment the package is re-built on bioconductor, your changes would vanish.

**Comment by stedy** [comment]
Ok gotcha, will rollback that commit and edit the Rmd and then send a PR on that

**Pull request closed without merging**
